[package]
name = "decoy"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
colored = "3.0.0"
fuzzy-matcher = "0.3.7"
inquire = "0.7.5"
itertools = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
tap = "1.0.1"
